% tempEEG = load('/ssd/zhibin/1overf/20220515_2P/Segmented_data/1_50Hz_ICAautomized/EEG20220515.mat'); 
% tempBP = load('/ssd/zhibin/1overf/20220515_2P/Segmented_data/1_50Hz_ICAautomized/BP20220515.mat');

% data(1,1).EEG = tempEEG.EEGCondi1L;
% data(1,2).EEG = tempEEG.EEGCondi1R;
% data(2,1).EEG = tempEEG.EEGCondi2L;
% data(2,2).EEG = tempEEG.EEGCondi2R;
% data(3,1).EEG = tempEEG.EEGCondi3L;
% data(3,2).EEG = tempEEG.EEGCondi3R;
% data(4,1).EEG = tempEEG.EEGCondi4L;
% data(4,2).EEG = tempEEG.EEGCondi4R;
% data(1,1).BP = tempBP.BPCondi1L;
% data(1,2).BP = tempBP.BPCondi1R;
% data(2,1).BP = tempBP.BPCondi2L;
% data(2,2).BP = tempBP.BPCondi2R;
% data(3,1).BP = tempBP.BPCondi3L;
% data(3,2).BP = tempBP.BPCondi3R;
% data(4,1).BP = tempBP.BPCondi4L;
% data(4,2).BP = tempBP.BPCondi4R;

data(1,1).EEG = EEGCondi1L;
data(1,2).EEG = EEGCondi1R;
data(2,1).EEG = EEGCondi2L;
data(2,2).EEG = EEGCondi2R;
data(3,1).EEG = EEGCondi3L;
data(3,2).EEG = EEGCondi3R;
data(4,1).EEG = EEGCondi4L;
data(4,2).EEG = EEGCondi4R;

data(1,1).BP = BPCondi1L;
data(1,2).BP = BPCondi1R;
data(2,1).BP = BPCondi2L;
data(2,2).BP = BPCondi2R;
data(3,1).BP = BPCondi3L;
data(3,2).BP = BPCondi3R;
data(4,1).BP = BPCondi4L;
data(4,2).BP = BPCondi4R;

data(1,1).FB = FBCondi1L;
data(1,2).FB = FBCondi1R;
data(2,1).FB = FBCondi2L;
data(2,2).FB = FBCondi2R;
data(3,1).FB = FBCondi3L;
data(3,2).FB = FBCondi3R;
data(4,1).FB = FBCondi4L;
data(4,2).FB = FBCondi4R;

data(1,1).EMG = EMGCondi1L;
data(1,2).EMG = EMGCondi1R;
data(2,1).EMG = EMGCondi2L;
data(2,2).EMG = EMGCondi2R;
data(3,1).EMG = EMGCondi3L;
data(3,2).EMG = EMGCondi3R;
data(4,1).EMG = EMGCondi4L;
data(4,2).EMG = EMGCondi4R;

data(1,1).Pacer = PacerCondi1L;
data(1,2).Pacer = PacerCondi1R;
data(2,1).Pacer = PacerCondi2L;
data(2,2).Pacer = PacerCondi2R;
data(3,1).Pacer = PacerCondi3L;
data(3,2).Pacer = PacerCondi3R;
data(4,1).Pacer = PacerCondi4L;
data(4,2).Pacer = PacerCondi4R;

data(1,1).FBlocs = FBlocsCondi1L;
data(1,2).FBlocs = FBlocsCondi1R;
data(2,1).FBlocs = FBlocsCondi2L;
data(2,2).FBlocs = FBlocsCondi2R;
data(3,1).FBlocs = FBlocsCondi3L;
data(3,2).FBlocs = FBlocsCondi3R;
data(4,1).FBlocs = FBlocsCondi4L;
data(4,2).FBlocs = FBlocsCondi4R;

%%
save(['data' num2str(seed) '.mat'],'EEGCondi1L','EEGCondi2L','EEGCondi3L',...
    'EEGCondi4L','EEGCondi5L','EEGCondi6L',...
    'EEGCondi1R','EEGCondi2R','EEGCondi3R',...
    'EEGCondi4R','EEGCondi5R','EEGCondi6R',...
    'BPCondi1L','BPCondi2L','BPCondi3L',...
    'BPCondi4L','BPCondi5L','BPCondi6L',...
    'BPCondi1R','BPCondi2R','BPCondi3R',...
    'BPCondi4R','BPCondi5R','BPCondi6R',...
    'FBCondi1L','FBCondi2L','FBCondi3L',...
    'FBCondi4L','FBCondi5L','FBCondi6L',...
    'FBCondi1R','FBCondi2R','FBCondi3R',...
    'FBCondi4R','FBCondi5R','FBCondi6R',...
    'EMGCondi1L','EMGCondi2L','EMGCondi3L',...
    'EMGCondi4L','EMGCondi5L','EMGCondi6L',...
    'EMGCondi1R','EMGCondi2R','EMGCondi3R',...
    'EMGCondi4R','EMGCondi5R','EMGCondi6R',...
    'FBlocsCondi1L','FBlocsCondi2L','FBlocsCondi3L',...
    'FBlocsCondi4L','FBlocsCondi5L','FBlocsCondi6L',...
    'FBlocsCondi1R','FBlocsCondi2R','FBlocsCondi3R',...
    'FBlocsCondi4R','FBlocsCondi5R','FBlocsCondi6R',...
    'conditionNames','labels',...
    'channels_infoL','channels_infoR');
    
    
    
    


% if 5 conditions
save(['data' num2str(seed) '.mat'],'EEGCondi1L','EEGCondi2L','EEGCondi3L',...
    'EEGCondi4L','EEGCondi5L',...
    'EEGCondi1R','EEGCondi2R','EEGCondi3R',...
    'EEGCondi4R','EEGCondi5R',...
    'BPCondi1L','BPCondi2L','BPCondi3L',...
    'BPCondi4L','BPCondi5L',...
    'BPCondi1R','BPCondi2R','BPCondi3R',...
    'BPCondi4R','BPCondi5R',...
    'FBCondi1L','FBCondi2L','FBCondi3L',...
    'FBCondi4L','FBCondi5L',...
    'FBCondi1R','FBCondi2R','FBCondi3R',...
    'FBCondi4R','FBCondi5R',...
    'EMGCondi1L','EMGCondi2L','EMGCondi3L',...
    'EMGCondi4L','EMGCondi5L',...
    'EMGCondi1R','EMGCondi2R','EMGCondi3R',...
    'EMGCondi4R','EMGCondi5R',...
    'FBlocsCondi1L','FBlocsCondi2L','FBlocsCondi3L',...
    'FBlocsCondi4L','FBlocsCondi5L',...
    'FBlocsCondi1R','FBlocsCondi2R','FBlocsCondi3R',...
    'FBlocsCondi4R','FBlocsCondi5R',...
    'conditionNames','labels',...
    'channels_infoL','channels_infoR','srL','srR');
    

%% eperiment
expt_data.allPerm=allPerm;
expt_data.conditionNames=conditionNames;
expt_data.EEGlabels=labels;

save(['expt_data' num2str(seed) '.mat'],'allPerm','conditionNames','labels');

save(['other_info' num2str(seed) '.mat'],'allPerm','conditionNames',...
    'labels','channels_infoL','channels_infoR','srL','srR');

%% plot
% just create some files to run
expt_data.colors.red
