function h = gui_init()

% Create the main window
a=get(0,'ScreenSize');
   h.hFig=figure( ...
      'BusyAction', 'cancel',...
      'Color', 'black', ...
      'Interruptible', 'on',...
      'Menubar','none',...
      'Name',' ', ...
      'NumberTitle','off', ...
      'Position', [0, 0, a(3), a(4)],... % should get the screen size to determine the width and height
      'Resize','off',...
      'RendererMode','manual',...
      'WindowStyle','normal',...
      'Visible','On');
   clear a;
   
% Set up the Text Window
top=0.75;
left=0.25;
right=0.85;
bottom=0.35;  
txtPos=[left bottom (right-left) top-bottom];
h.hText=uicontrol( ...
    'BackgroundColor','black', ...
    'BusyAction', 'cancel',...
    'Enable','inactive',...
    'FontName', 'Times New Roman',...
    'FontSize', 30,...
    'ForegroundColor', 'white',...
    'HorizontalAlignment','center', ...
    'Interruptible', 'off',...
    'Max',10, ...
    'Style','text', ...
    'String','Welcome!',...
    'Units','normalized',...
    'Position',txtPos,...
    'Visible','on');
clear top left right bottom txtPos;
 
h.hLbl1 =  uicontrol( ...
    'BackgroundColor','black', ...
    'BusyAction', 'cancel',...
    'Enable','inactive',...
    'FontSize', 14,...
    'ForegroundColor', 'white',...
    'HorizontalAlignment','left', ...
    'Interruptible', 'off',...
    'Max',1, ...
    'Style','text', ...
    'String','Subject Code:',...
    'Units','normalized',...
    'Position',[0.05 0.85 0.12 0.035]);  
   
h.hEdt1=uicontrol( ...
    'BackgroundColor','black', ...
    'BusyAction', 'cancel',...
    'Enable','on',...
    'FontSize', 14,...
    'ForegroundColor', 'white',...
    'HorizontalAlignment','left', ...
    'Interruptible', 'off',...
    'Max',1, ...
    'Style','edit', ...
    'String',[],...
    'Units','normalized',...
    'Position',[0.05 0.8 0.12 0.035]);

h.hLbl2 =  uicontrol( ...
    'BackgroundColor','black', ...
    'BusyAction', 'cancel',...
    'Enable','inactive',...
    'FontSize', 14,...
    'ForegroundColor', 'white',...
    'HorizontalAlignment','left', ...
    'Interruptible', 'off',...
    'Max',1, ...
    'Style','text', ...
    'String','Subject Age:',...
    'Units','normalized',...
    'Position',[0.05 0.75 0.12 0.035]);  
   
h.hEdt2=uicontrol( ...
    'BackgroundColor','black', ...
    'BusyAction', 'cancel',...
    'Enable','on',...
    'FontSize', 14,...
    'ForegroundColor', 'white',...
    'HorizontalAlignment','left', ...
    'Interruptible', 'off',...
    'Max',1, ...
    'Style','edit', ...
    'String',[],...
    'Units','normalized',...
    'Position',[0.05 0.7 0.12 0.035]);

h.hLbl3 =  uicontrol( ...
    'BackgroundColor','black', ...
    'BusyAction', 'cancel',...
    'Enable','inactive',...
    'FontSize', 14,...
    'ForegroundColor', 'white',...
    'HorizontalAlignment','left', ...
    'Interruptible', 'off',...
    'Max',1, ...
    'Style','text', ...
    'String','Test Ear:',...
    'Units','normalized',...
    'Position',[0.05 0.65 0.12 0.035]);  
   
h.hEdt3=uicontrol( ...
    'BackgroundColor','black', ...
    'BusyAction', 'cancel',...
    'Enable','on',...
    'FontSize', 14,...
    'ForegroundColor', 'white',...
    'HorizontalAlignment','left', ...
    'Interruptible', 'off',...
    'Max',2, ...
    'Style','popupmenu', ...
    'String',{'both','no other'},...
    'Units','normalized',...
    'Position',[0.05 0.6 0.12 0.035]);

h.hPB = uicontrol( ...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.05 0.5 0.12 0.035],...
    'HorizontalAlignment','center',...
    'FontSize',14,...
    'String','Run');

h.hLbl4 =  uicontrol( ...
    'BackgroundColor','black', ...
    'BusyAction', 'cancel',...
    'Enable','inactive',...
    'FontSize', 14,...
    'ForegroundColor', 'white',...
    'HorizontalAlignment','center', ...
    'Interruptible', 'off',...
    'Max',2, ...
    'Style','text', ...
    'String',[],...
    'Units','normalized',...
    'Position',[0.7 0.9 0.3 0.07]);  


drawnow;
set(h.hPB,'Callback',{@runbutton,h});

waitfor(h.hPB,'Enable');

end